# Camera
USE_CAMERA_STUB := true

# Legacy HAL
TARGET_HAS_LEGACY_CAMERA_HAL1 := true

#Camera Wrappers
USE_MTK_CAMERA_WRAPPER := true

MTK_MEDIA_PROFILES := true
BOARD_USES_MTK_MEDIA_PROFILES := true
